#!/bin/sh
#
# setup a fresh unix v6 system from tape.
# note: this will erase your previous system!
#

if [ -e rk0 -o -e rk1 -o -e rk2 ] ; then 
    if [ $# -ne 1 -o "x$1" != "xy" ] ; then
        echo "This will wipe your current v6 system!  Run with 'y' on command"
        echo "line to confirm!"
        echo
        echo "usage:  $0 y"
        exit 1
    fi
    rm -f rk[012]
fi

if [ ! -f dist.tap ] ; then
    gzip -dc dist.tap.gz > dist.tap
fi

./runsetup
./runsetup2
